name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # Allows manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint package.json
        uses: bvandrc/lint-package-json@v2

      - name: Lint & Type Check
        run: pnpm check

  readme-up-to-date:
    name: README Up To Date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build README
        run: pnpm build:readme

      - name: Check for drift
        run: git diff --exit-code README.md
